# Generated by Django 3.2.8 on 2021-10-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posted_by',
        ),
        migrations.AddField(
            model_name='post',
            name='posted_by',
            field=models.ManyToManyField(to='posts.Moderator'),
        ),
    ]
