# Generated by Django 3.2.8 on 2021-10-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211020_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title1',
            field=models.CharField(max_length=100),
        ),
    ]
