# Generated by Django 3.2.8 on 2021-10-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_title1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube',
            field=models.CharField(blank=True, default='link here', max_length=2000),
        ),
    ]
