# Generated by Django 3.2.8 on 2021-10-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
